spring:
  application:
    name: web
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?useSSL=false&serverTimezone=Asia/Tokyo
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  security:
    user:
      name: sample # ユーザー名
      password: password # パスワード
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.recipe.domain.entity